## first: kubectl apply -f kubefiles/elastic_cloud.yaml
## https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html

---
kind: Namespace
apiVersion: v1
metadata:
  name: elastic-cloud
  # labels:
  #   app.kubernetes.io/name: elastic-cloud
  #   app.kubernetes.io/part-of: elastic-cloud

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-cloud
  namespace: elastic-cloud
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false

---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic-cloud
  namespace: elastic-cloud
spec:
  version: 7.6.2
  count: 1
  elasticsearchRef:
    name: elastic-cloud
